config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  resources :orders
  put "/cart_items/:id/decrease", to: "cart_items#decrease"
  put "/cart_items/:id/increase", to: "cart_items#increase"
  resources :cart
  resources :cart_items
  put "/menus/:id/details", to: "menus#update_details"
  resources :menus
  resources :menu_items
  resources :users
  get "/reports", to: "orders#get_report"
  post "/reports", to: "orders#show_report"
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :session
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="Navbar">
      <h2 class="Navbar-brand">COCO Cafe</h2>
      <ul class="Navbar-container">
        <% if @current_user %>
          <li class="Navbar-item"><%= link_to "Menu", menus_path %></li>
          <li class="Navbar-item"><%= link_to "Cart", cart_index_path %></li>
          <% if @current_user.is_owner %>
            <li class="Navbar-item"><%= link_to "Menu Items", menu_items_path %></li>
            <li class="Navbar-item"><%= link_to "Orders", orders_path %></li>
            <li class="Navbar-item"><%= link_to "Users", users_path %></li>
            <li class="Navbar-item"><%= link_to "Reports", reports_path %></li>
          <% elsif @current_user.is_clerk %>
            <li class="Navbar-item"><%= link_to "Orders", orders_path %></li>
          <% else %>
            <li class="Navbar-item"><%= link_to "Your Orders", orders_path %></li>
          <% end %>
          <% if @current_user.avatar.attached? %>
            <li class="Navbar-item">
              <%= link_to cl_image_tag(@current_user.avatar.key, :effect=>"sharpen:100", :height=>42, :radius=>30, :width=>42, :crop=>"scale", :format=>"PNG"), "/users/#{@current_user.id}/edit" %>
            </li>
          <% else %>
            <li class="Navbar-item">
              <%= link_to "Edit Profile", "/users/#{@current_user.id}/edit" %>
            </li>
          <% end %>
          <li class="Navbar-item"><%= link_to "Sign-out", destroy_session_path, method: "delete" %></li>
        <% else %>
          <li class="Navbar-item"><%= link_to "Home", "/" %></li>
          <li class="Navbar-item">
            <div class="Navbar-item-highlight">
              <%= link_to "Sign-up", new_user_path %>
            </div>
          </li>
          <li class="Navbar-item"><%= link_to "Sign-in", new_session_path %></li>
        <% end %>
      </ul>
    </nav>

    <% if @current_user %>
      <nav class="UserInformationBar">
        <h2 class="UserInformationBar-text">Welcome, <%= @current_user.name %> (<%= @current_user.role %>)</h2>
      </nav>
    <% end %>

    <% if flash[:error] %>
      <p class="FlashError">
        <%= flash[:error] %>
      </p>
    <% end %>

    <% if flash[:success] %>
      <p class="FlashSuccess">
        <%= flash[:success] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>